### ISSUE TITLE
"feedly-unread-favicon.js" slows down my Feedly/browser (Vivaldi+Tampermonkey)

### ISSUE THREAD

**Issue by fajfka** [dmahr1/feedly-enhancer-chrome#1]
Hello, Dan.

I detect a "slow-down" problem when your script is activated in Tampermonkey in Vivaldi. After refreshing the Feedly page, everything "hangs" and can't be a moment (1-2 seconds, probably until the page is loaded), I not able open another article, another Feed, etc. There is the same situation when I put your script into the Chrome User Script Handler addon. I tried Tampermonkey with your script under Chrome, although it is significantly better, but the delay is also noticeable. Could you somehow check if there is any problem, please?

The original Feedly Unread Count script in Favicon and Title Bar by Matthew Wilkin was used earlier in GreaseMonkey under Firefox and there it was OK, and with the script modified by Wout Bittremieux https://github.com/bittremieux/feedly-unread, it was OK, too. Then I moved from FF to Vivaldi, Bittremieux modification from June 2017 also worked well.
I found your edited script about 10 days ago, after Feedly.com's last redesign, when I was frustrated that I no longer had my favorite feature. Thanks for the adjustment.
But I have to leave the script off for now, because it's a bit uncomfortable on my few PCs and browsers.

Thanks for your time, and sorry for my bad english.
Petr F.

**Comment by dmahr1** [comment]
Wow, I never knew anyone else used this. I don't know which fork of the addon will work in Vivaldi @fajfka. I recommend you take whatever version _does_ work in Vivaldi without slowdowns and applying the small change necessary for the latest version of Feedly. All I had to do was change the unread selector from `categoryUnreadCount` to `streamUnreadCount`. See [this commit](https://github.com/dmahr1/feedly-enhancer-chrome/commit/f2984429d8e1049f9aef1a7eb40ebaedd70c4d42) for details. Good luck.

**Comment by fajfka** [comment]
Hi Dan. Thanks for your reply. That script it started to work again a few days before your answer. so it was in Vivaldi either colliding with something else, or (that's more likely) the guys from Feedly had some bugs in the code and they fixed it. Anyway, today's OK :-)
Thanks and nice day.
