### ISSUE TITLE
"feedly-unread-favicon.js" stopped working after Feedly redesign August 30, 2019

### ISSUE THREAD

**Issue by fajfka** [dmahr1/feedly-enhancer-chrome#2]
Hi Dan.
I know I write very soon, just a few hours after Feedly put in a new design, but your script is very useful, so I hope you'll ever have the time and mood to edit the script for a new version of Feedly.
Thank you very much in advance!

Petr F.

**Comment by dmahr1** [comment]
@fajfka Oh wow, I just got the redesign myself. There are a lot of changes so it'll take me a little while to update this script. I'll ping you when it's done, though.

**Comment by dmahr1** [comment]
@fajfka Just updated both the layout script and the favicon script.
